---
title: "R Notebook"
output: html_notebook
---

#read data
```{r}
sift.features=read.csv("../data/sift_features.csv", header = T)
label=read.csv("../data/labels.csv")

source("../lib/train.baseline.r")
source("../lib/test.baseline.r")
```

#train and test
```{r}
all=data.frame(cbind(label,t(sift.features)))
test.index1=c(1:200,1001:1200)
colnames(all)[1]="y"
test=all[test.index1,]
train=all[-test.index1,]
```

#baseline
```{r}
baseline.model=train.baseline(train)
baseline.pre=test.baseline(baseline.model,test)
table(baseline.pre,test$y)
```













#tree depth=6
```{r}
gbm2=gbm(y~.,data=all,dist="adaboost",n.tree = 100,shrinkage = 0.1,interaction.depth = 5)
m=gbm.perf(gbm2)
confusionMatrix( predict(gbm2,train,n.trees =m)>0,train$y >0)$table
confusionMatrix( predict(gbm2,test,n.trees =m)>0,test$y >0)$table

test.x=test[,-1]
test.y=as.factor(test[,1])


train(
  test.x, 
  test.y, 
  method="gbm", 
  tuneGrid=expand.grid(
    n.trees=100,
    interaction.depth=1:10,
    shrinkage=.1,
    n.minobsinnode=10
    ), 
  distribution="multinomial")
```