---
title: "R Notebook"
output: html_notebook
---



#install packages
```{r}
packages.used=c("gbm", "caret","DMwR" ,"nnet","randomForest")

# check packages that need to be installed.
packages.needed=setdiff(packages.used, 
                        intersect(installed.packages()[,1], 
                                  packages.used))
# install additional packages
if(length(packages.needed)>0){
  install.packages(packages.needed, dependencies = TRUE)
}

```

#read data
```{r,warning=F}
sift.features=read.csv("../data/sift_features.csv", header = T)
lbp=read.csv("../data/lbp.csv", header = F)

label=read.csv("../data/labels.csv")

source("../lib/train.r")
source("../lib/test.r")

```

#train and test 
```{r}
all=data.frame(cbind(label,t(sift.features)))
test.index=sample(1:2000,400,replace=F)
colnames(all)[1]="y"
test.sift=all[test.index,]
test.x.sift=test.sift[,-1]
train.sift=all[-test.index,]
```


#baseline
```{r,warnings=F}
start.time <- Sys.time()
baseline.model=train.baseline(train.sift)
baseline.pre=test.baseline(baseline.model,test.x.sift)
table(baseline.pre,test.sift$y)
end.time <- Sys.time()
end.time - start.time

```

#new features
```{r}
new.data=data.frame(cbind(label,lbp))
colnames(new.data)[1]="y"
test=new.data[test.index,]
test.x=test[,-1]
train=new.data[-test.index,]
```



#baseline using new features
```{r}
start.time <- Sys.time()
baseline.model=train.baseline(train)
baseline.pre=test.baseline(baseline.model,test.x)
table(baseline.pre,test$y)
end.time <- Sys.time()
end.time - start.time
```

#bp
```{r}
start.time <- Sys.time()

bp.model=train.bp(train)
bp.pre=test.bp(bp.model,test.x)
table(bp.pre,test$y)

end.time <- Sys.time()
end.time - start.time
```

#random forest
```{r}
start.time <- Sys.time()

rf.model=train.rf(train)
rf.pre=test.rf(rf.model,test.x)
table(rf.pre,test$y)

end.time <- Sys.time()
end.time - start.time

```


#svm
```{r}
start.time <- Sys.time()

source("../lib/train.r")
svm.model=train.svm(train)
svm.pre=test.svm(svm.model,test.x)
table(svm.pre,test$y)

end.time <- Sys.time()
end.time - start.time

```

#logistic
```{r}
start.time <- Sys.time()

log.model=train.log(train)
log.pre=test.log(log.model, test.x)
table(log.pre, test$y)

end.time <- Sys.time()
end.time - start.time

```


#majority vote
```{r}
pre=(as.numeric(as.character(bp.pre))+as.numeric(as.character(log.pre))+as.numeric(as.character(svm.pre)))

pre=ifelse(pre>=2,1,0)



table(pre,test$y)

```

#error rate
```{r}
start.time <- Sys.time()

source("../lib/cross_validation.R")
cv.function(train, 5)

end.time <- Sys.time()
end.time - start.time

```


